name: Dock
run-name: run Docker
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Docker instalation
        run: |
          sudo apt-get remove containerd.io
          sudo apt install docker.io docker-compose -y
      - name: Create image
        run: docker build -t builder .
      - name: Run container
        run: docker run --name test -t builder ls
      - name: Copy log file
        run: docker cp test:/repo/log.txt ./log.txt
      - name: data
        uses: actions/upload-artifact@v4
        with:
          name: docker_artifact
          path: /home/runner/work/laba8/laba8/log.txt

